# Generated by Django 2.1 on 2018-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-posted'],
            },
        ),
    ]
