# Generated by Django 2.1.1 on 2018-09-10 12:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20180903_1806'),
        ('articles', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='club',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='user', chained_model_field='club', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.Club'),
        ),
    ]
