# Generated by Django 2.1.1 on 2018-09-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180910_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='me',
        ),
        migrations.AlterField(
            model_name='post',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.Club'),
        ),
    ]
