# Generated by Django 2.1.1 on 2018-09-10 17:48

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180910_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image_credit',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
