# Generated by Django 2.1 on 2018-08-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20180831_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='club',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
