# Generated by Django 2.1.1 on 2018-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20180831_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
