# Generated by Django 2.1.1 on 2018-09-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20180910_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
