# Generated by Django 2.1.1 on 2018-09-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0001_initial'),
        ('accounts', '0020_auto_20180902_1156'),
        ('clubs', '0004_auto_20180903_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league_contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
                ('sponsor_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sponsors.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('teams', models.ManyToManyField(to='clubs.Team')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('sf', models.IntegerField()),
                ('sa', models.IntegerField()),
                ('sq', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('pe', models.IntegerField()),
                ('pq', models.IntegerField()),
                ('points', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.LeagueTable')),
                ('team', models.ManyToManyField(to='clubs.Team')),
            ],
        ),
    ]
