# Generated by Django 2.1.1 on 2018-09-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20180903_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='age_group',
            field=models.CharField(choices=[('Senior', 'Senior'), ('U23', '23'), ('U21', 'U21'), ('U20', 'U20'), ('U18', 'U18'), ('U17', 'U17'), ('U16', 'U16')], default='Senior', max_length=6),
        ),
    ]
