# Generated by Django 2.1.1 on 2018-09-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_club_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
