# Generated by Django 2.1.1 on 2018-09-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_auto_20180902_1156'),
        ('clubs', '0003_auto_20180831_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_end_date', models.DateField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.Club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_end_date', models.DateField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('info', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_end_date', models.DateField(blank=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.Sponsor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.Team')),
            ],
        ),
        migrations.AddField(
            model_name='playersponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.Sponsor'),
        ),
        migrations.AddField(
            model_name='clubsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.Sponsor'),
        ),
    ]
