# Generated by Django 2.1.1 on 2018-09-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0005_auto_20180904_1339'),
        ('accounts', '0020_auto_20180902_1156'),
        ('clubs', '0004_auto_20180903_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.League')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a', to='clubs.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b', to='clubs.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Match')),
                ('team_a_squad', models.ManyToManyField(related_name='team_a_squad', to='accounts.Profile')),
                ('team_b_squad', models.ManyToManyField(related_name='team_b_squad', to='accounts.Profile')),
            ],
        ),
    ]
