# Generated by Django 2.1.1 on 2018-09-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.BooleanField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.A')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.B')),
            ],
        ),
        migrations.AddField(
            model_name='a',
            name='things',
            field=models.ManyToManyField(through='fixtures.ThroughModel', to='fixtures.B'),
        ),
    ]
