# Generated by Django 2.1.1 on 2018-09-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_a_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='things',
        ),
        migrations.RemoveField(
            model_name='throughmodel',
            name='a',
        ),
        migrations.RemoveField(
            model_name='throughmodel',
            name='b',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='ThroughModel',
        ),
    ]
