# Generated by Django 2.1.1 on 2018-09-04 22:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_profile_team'),
        ('clubs', '0004_auto_20180903_1806'),
        ('fixtures', '0007_auto_20180904_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='a_squad',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='team_a', chained_model_field='team', horizontal=True, to='accounts.Profile', verbose_name='a_squad'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='team_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='test_team_a', to='clubs.Team'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='team_b',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='test_team_b', to='clubs.Team'),
        ),
    ]
