# Generated by Django 2.1.1 on 2018-09-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0009_auto_20180904_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='a_squad',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='team_b',
        ),
    ]
