# Generated by Django 2.1.1 on 2018-09-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0013_auto_20180904_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='team_a_squad',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='team_b_squad',
        ),
    ]
