# Generated by Django 2.1.1 on 2018-09-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0014_auto_20180904_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='team_a',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='test_team_a', to='clubs.Team'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='team_b',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='test_team_b', to='clubs.Team'),
        ),
    ]
