# Generated by Django 2.1.1 on 2018-09-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0015_auto_20180904_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='a_squad',
            new_name='team_a_squad',
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='b_squad',
            new_name='team_b_squad',
        ),
    ]
