# Generated by Django 2.1 on 2018-08-31 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20180831_2327'),
        ('accounts', '0002_auto_20180831_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='roles',
            new_name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
            preserve_default=False,
        ),
    ]
