# Generated by Django 2.1 on 2018-08-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180901_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='Position',
            field=models.CharField(choices=[('Coach', 'Coach'), ('Press Officer', 'Press Officer'), ('Referees', 'Referees'), ('Wing Spiker', 'Wing Spiker'), ('Attacker', 'Attacker'), ('Setter', 'Setter'), ('Centre', 'Centre'), ('Libero', 'Libero'), ('Defensive Specalist', 'Defensive Specalist')], default='Coach', max_length=50),
        ),
    ]
