# Generated by Django 2.1 on 2018-08-31 23:20

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180901_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='Position',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='role', chained_model_field='role', on_delete=django.db.models.deletion.CASCADE, to='accounts.Position'),
        ),
    ]
