# Generated by Django 2.1 on 2018-09-02 10:22

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180901_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='role', chained_model_field='role', horizontal=True, to='accounts.Position'),
        ),
    ]
