# Generated by Django 2.1.1 on 2018-09-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180902_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(to='accounts.Role'),
        ),
    ]
