# Generated by Django 2.1.1 on 2018-09-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180904_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(to='accounts.Position'),
        ),
    ]
