# Generated by Django 2.1.1 on 2018-09-04 21:15

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180904_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='role', chained_model_field='role', horizontal=True, to='accounts.Position', verbose_name='position'),
        ),
    ]
