# Generated by Django 2.1.1 on 2018-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20180903_1806'),
        ('accounts', '0024_auto_20180904_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(to='clubs.Team'),
        ),
    ]
